version: 2
updates:
# Fetch and update latest `github-actions` pkgs
- package-ecosystem: github-actions
  directory: '/'
  schedule:
    interval: daily
    time: '00:00'
  open-pull-requests-limit: 10
  reviewers:
    - techtoto
  assignees:
    - techtoto
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
  # Fetch and update latest `gradle` pkgs
- package-ecosystem: gradle
  directory: '/'
  schedule:
    interval: daily
    time: '00:00'
  open-pull-requests-limit: 10
  reviewers:
    - techtoto
  assignees:
    - techtoto
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
