name: Gradle CI
on:
  push:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-20.04
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3.8.0
        with:
          java-version: 16
          distribution: 'adopt'
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          key: "$GITHUB_SHA"
          path: |
            ~/builds
            ~/build
            ~/.gradle
      - name: Build with Gradle
        run: chmod +x ./gradlew && ./gradlew installDist
